project:
  type: book
  output-dir: _book
  resources:
    - assets/gert-logo.png
    - assets/gert-favicon-32.ico

jupyter: julia-1.10

book:
  title: "Graph Equilibrium Radiative Transfer"
  subtitle: "Analytic Solutions and Computational Methods"
  author: "Nikolaj Maack Bielefeld"
  date: today
  chapters:
    - index.qmd
    - preface.qmd
    
    - part: "Part I: Introduction and Overview"
      chapters:
        - chapters/p1-ch1-literature-review.qmd
        - chapters/p1-ch2-methodology-overview.qmd
        - chapters/p1-ch3-roadmap.qmd
    
    - part: "Part II: Domain and Geometry Setup"
      chapters:
        - chapters/p2-ch1-geometry-concepts.qmd
        - chapters/p2-ch2-2d-geometry-setup.qmd
        - chapters/p2-ch3-3d-geometry-setup.qmd
    
    - part: "Part III: Exchange Factor Transformation"
      chapters:
        - chapters/p3-ch1-exchange-factor-concepts.qmd
        - chapters/p3-ch2-exchange-factor-2d-applications.qmd
        - chapters/p3-ch3-exchange-factor-3d-applications.qmd
        - chapters/p3-ch4-exchange-factor-theory-proofs.qmd
    
    - part: "Part IV: Exchange Factor Smoothing"
      chapters:
        - chapters/p4-ch1-smoothing-concepts.qmd
        - chapters/p4-ch2-smoothing-demonstrations.qmd
        - chapters/p4-ch3-smoothing-theory-proofs.qmd
    
    - part: "Part V: Anisotropic Extension"
      chapters:
        - chapters/p5-ch1-anisotropic-concepts.qmd
        - chapters/p5-ch2-anisotropic-2d-applications.qmd
        - chapters/p5-ch3-anisotropic-3d-applications.qmd
        - chapters/p5-ch4-anisotropic-theory-proofs.qmd
    
    - part: "Part VI: Spectral Extension"
      chapters:
        - chapters/p6-ch1-spectral-concepts.qmd
        - chapters/p6-ch2-spectral-2d-applications.qmd
        - chapters/p6-ch3-spectral-3d-applications.qmd
        - chapters/p6-ch4-spectral-theory-proofs.qmd
    
    - part: "Part VII: Beyond Radiative Transfer"
      chapters:
        - chapters/p7-ch1-directed-graphs.qmd
        - chapters/p7-ch2-general-applications.qmd
        - chapters/p7-ch3-future-directions.qmd
    
    - references.qmd

  navbar:
    search: true
    logo: assets/gert-logo.png
    title: "Graph Equilibrium Radiative Transfer"
    
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: true
    html-math-method: katex
    number-sections: true
    number-depth: 3
    logo: assets/gert-logo.png
    favicon: assets/gert-favicon-32.ico
    include-in-header: |
      <link rel="icon" type="image/x-icon" href="assets/gert-favicon-32.ico">
      <link rel="shortcut icon" type="image/x-icon" href="assets/gert-favicon-32.ico">
    crossref:
      chapters: true
      eq-prefix: "Eq."
      fig-prefix: "Fig."
      tbl-prefix: "Table"
      thm-prefix: "Theorem"
    
bibliography: references.bib
link-citations: true
reference-location: document

execute:
  freeze: auto
  cache: true
  echo: true
  output: true