project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - papers.qmd
    - about.qmd
    - examples/index.qmd
    - examples/example-01.qmd
    - examples/example-02.qmd
    - examples/example-03.qmd
    - examples/example-04.qmd
    - examples/example-05.qmd
    - examples/example-06.qmd
    - examples/example-07.qmd
    - examples/example-08.qmd
    - examples/example-09.qmd
        
jupyter: julia-1.13

website:
  title: "Graph Equilibrium Radiative Transfer"
  site-url: https://gert.net
  favicon: favicon-transparent.ico
  navbar:
    logo: assets/logo-transparent.png
    left:
      - href: index.qmd
        text: Home
      - href: papers.qmd
        text: Papers
      - href: examples/index.qmd
        text: Examples
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/NikoBiele/RayTraceHeatTransfer.jl
        aria-label: RayTraceHeatTransfer.jl on GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-tools: true
    html-math-method: katex
    crossref:
      eq-prefix: "Eq."
      fig-prefix: "Fig."
      tbl-prefix: "Table"
      thm-prefix: "Theorem"

bibliography: references.bib
link-citations: true

date-modified: last-modified
date-format: "D MMMM YYYY"
language:
  title-block-modified: "Last updated"

execute:
  freeze: auto
  cache: true
  echo: true
  output: true