name: Render and Publish

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'

      - name: Cache Julia
        uses: julia-actions/cache@v1

      - name: Install Julia dependencies (CI = releases)
        shell: julia --project=. {0}
        run: |
          using Pkg
          isfile("Manifest.toml") && Pkg.update("RayTraceHeatTransfer")
          Pkg.instantiate()
          Pkg.precompile()

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        if: contains(github.ref, 'main')
        with:
          path: _book

      - name: Deploy to GitHub Pages
        id: deployment
        if: contains(github.ref, 'main')
        uses: actions/deploy-pages@v4